name: qa4sm-autoreports
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - cartopy
  - xarray
  - netCDF4
  - pip
  - pip:
      - qa4sm-api
      - pyyaml
      - pytest
      - black