# This workflow will install Python dependencies and run tests on
# windows and linux systems with a variety of Python versions

# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Automated Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  build:
    name: py${{ matrix.python-version }}@${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.12']
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags --force
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channel-priority: flexible
          activate-environment: qa4sm_autoreports
          auto-activate-base: false
      - name: Print environment infos
        shell: bash -l {0}
        run: |
          conda info -a
          conda list
          pip list
          which pip
          which python
      - name: Install dependencies and package
        shell: bash -l {0}
        run: |
          pip install build -e .[testing]
      - name: Run all tests
        shell: bash -l {0}
        env:  # so some of the optional tests can log in to test.qa4sm.eu
          QA4SM_INSTANCE: ${{ secrets.QA4SM_INSTANCE }}
          QA4SM_TOKEN: ${{ secrets.QA4SM_TOKEN }}
        run: |
          # Integration tests trigger runs and send notifications, for now excluded from the CI
          pytest -m "not integration"
      - name: Export Environment
        shell: bash -l {0}
        run: |
          mkdir -p artifacts
          filename=env_py${{ matrix.python-version }}_${{ matrix.os }}.yml
          conda env export --no-builds | grep -v "prefix" > artifacts/$filename

  coveralls:
    name: Submit Coveralls 👚
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Finalize Coveralls Parallel Build
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
        continue-on-error: true

  package:
    name: Build sdist & wheel 📦
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0  # needed for setuptools_scm to determine version
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Build sdist and wheel
        run: |
          pip install build twine
          python -m build
          ls -la dist/
          twine check dist/*
      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist/

  publish:
    name: Upload to PyPI 🚀
    if: startsWith(github.ref, 'refs/tags/v') && startsWith(github.repository, 'awst-austria')
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: |
          echo "GITHUB_REF = $GITHUB_REF"
          echo "GITHUB_REPOSITORY = $GITHUB_REPOSITORY"
      - name: Download distribution artifacts
        uses: actions/download-artifact@v6
        with:
          name: dist
          path: dist/
      - name: Display downloaded files
        run: ls -aR dist/
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          skip_existing: true
          verbose: true
          verify_metadata: true
          packages_dir: dist/
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }} # this needs to be uploaded to github actions secrets